Remove test for MALLOC conformance ... this can cause an undefined reference to rpl_malloc   Fixes #134
git-svn-id: https://svn.nexusformat.org/code/trunk@1093 ff5d1e40-2be0-497f-93bd-dc18237bd3c7